import { defineConfig, type Plugin } from 'vite';
import { createHash } from 'node:crypto';
import { execSync } from 'node:child_process';
import pkg from './package.json' with { type: 'json' };

/** What this build is: package version, commit and build time. Shown on the title screen. */
function buildInfo() {
  let sha = (process.env.GITHUB_SHA ?? '').slice(0, 7);
  if (!sha) {
    try { sha = execSync('git rev-parse --short=7 HEAD', { stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim(); } catch { sha = 'local'; }
  }
  return { version: pkg.version, sha, built: new Date().toISOString() };
}
const BUILD = buildInfo();

/**
 * Emits sw.js at build time: a cache-first service worker whose precache list is the
 * exact set of files in the build, versioned by their content, so a new build replaces
 * the old cache atomically and the game works offline after the first visit.
 */
function serviceWorker(): Plugin {
  return {
    name: 'brix-service-worker',
    apply: 'build',
    generateBundle(_options, bundle) {
      // non-Latin font subsets load on demand by unicode-range; they need not be precached
      const files = Object.keys(bundle).filter(f => !f.endsWith('.map') && !(f.endsWith('.woff2') && !/-latin-/.test(f)));
      const publicFiles = ['manifest.webmanifest', 'levels/original/levels.json', 'icons/icon.svg', 'icons/icon-192.png', 'icons/icon-512.png', 'icons/maskable-512.png', 'icons/apple-touch-icon.png'];
      const all = ['./', ...files, ...publicFiles];
      const hash = createHash('sha256');
      for (const f of files) {
        const item = bundle[f];
        hash.update(f).update(item.type === 'chunk' ? item.code : typeof item.source === 'string' ? item.source : Buffer.from(item.source));
      }
      const version = hash.digest('hex').slice(0, 12);
      // version.json is what an installed copy compares itself against, so it is never cached
      this.emitFile({ type: 'asset', fileName: 'version.json', source: JSON.stringify(BUILD) });
      const source = `// generated by vite.config.ts
const CACHE = 'brix-${version}';
const PRECACHE = ${JSON.stringify(all)};
self.addEventListener('install', e => {
  e.waitUntil(caches.open(CACHE).then(c => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', e => {
  e.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('brix-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', e => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== location.origin || url.pathname.endsWith('/version.json')) return;
  e.respondWith(caches.match(req, { ignoreSearch: true }).then(hit => hit || fetch(req).then(res => {
    if (res.ok) { const copy = res.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return res;
  }).catch(() => caches.match('./'))));
});
`;
      this.emitFile({ type: 'asset', fileName: 'sw.js', source });
    },
  };
}

export default defineConfig({
  base: './',
  plugins: [serviceWorker()],
  define: { __BUILD__: JSON.stringify(BUILD) },
  server: { port: 8129, strictPort: true },
  preview: { port: 8129, strictPort: true },
  build: { target: 'es2022', assetsInlineLimit: 0 },
  test: { include: ['tests/**/*.test.ts'] },
});
